language: bash
services: docker

env:
  - VERSION=1.11 VARIANT=stretch
  - VERSION=1.11 VARIANT=alpine3.8
  - VERSION=1.11 VARIANT=alpine3.7
  - VERSION=1.10 VARIANT=stretch
  - VERSION=1.10 VARIANT=alpine3.8
  - VERSION=1.10 VARIANT=alpine3.7

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION${VARIANT:+/$VARIANT}"
  - image="golang:$VERSION${VARIANT:+-$VARIANT}"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
